dist: trusty
services:
  - docker

stages:
  - test
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: test
      script:
        - docker build . -t torsocks:latest
        - docker run -d -p 9050:9050 torsocks
        - docker ps -a
        - sleep 10
        - docker logs --tail all $(docker ps -q --filter ancestor=torsocks)
        - curl -v -x socks5://127.0.0.1:9050 https://checkip.amazonaws.com
        - docker stop $(docker ps -q --filter ancestor=torsocks)
    - stage: deploy
      script:
        - docker login -u "$DOCKER_LOGIN" -p "$DOCKER_PASSWORD"
        - docker build . -t shpaker/torsocks:latest
        - docker run -d -p 9050:9050 shpaker/torsocks
        - CONTAINER_ID=$(docker ps -q --filter ancestor=shpaker/torsocks)
        - TOR_VERSION="$(docker exec ${CONTAINER_ID} tor --version | cut -d' ' -f 3)"
        - docker build . -t shpaker/torsocks:${TOR_VERSION}
        - docker images
        - docker push shpaker/torsocks
