dist: trusty
services:
  - docker

env:
  - DOCKER_REPO: torsocks
  - DOCKER_TAG: latest

stages:
- build
- test
- name: deploy
  if: branch = master

jobs:
  include:
    - stage: build
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN" --password-stdin
        - docker build . -t ${DOCKER_REPO}:${DOCKER_TAG}
        - docker images
    - stage: test
      script:
        - docker run -d -p 9050:9050 torsocks
        - docker ps -a
        - sleep 10
        - docker logs --tail all $(docker ps -q --filter ancestor=torsocks)
        - curl -v -x socks5://127.0.0.1:9050 https://checkip.amazonaws.com
    - stage: deploy
      script:
        - docker push ${DOCKER_REPO}
