name: Build

on:
  workflow_dispatch:
    inputs:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REGISTRY_HOST: ghcr.io
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to ${{ env.REGISTRY_HOST }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY_HOST }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Extract TOR version
        shell: bash
        run: |
          docker build . -t testing_torsocks
          docker run -d -p 9050:9050 testing_torsocks
          CONTAINER_ID=$(docker ps -q --filter ancestor=testing_torsocks)
          TOR_VERSION="$(docker exec ${CONTAINER_ID} tor --version | sed 's/[^0-9.]*\([0-9.]*\).*/\1/'"
          echo "##[set-output name=name;]$(echo ${GITHUB_REPOSITORY#*/})"
          echo "##[set-output name=ver;]$(echo ${TOR_VERSION})"
          docker stop ${CONTAINER_ID}
        id: extract_name_and_version
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            "${{ env.REGISTRY_HOST }}/${{ github.repository }}:latest"
            "${{ env.REGISTRY_HOST }}/${{ github.repository }}:${{ steps.extract_name_and_version.outputs.ver }}"
          labels:
            "org.opencontainers.image.source=https://github.com/${{ github.repository }}"
          build-args: |
            SHORTENER_VERSION=${{ steps.extract_name_and_version.outputs.ver }}
          cache-from: type=registry,ref=${{ env.REGISTRY_HOST }}/${{ github.repository }}:${{ steps.extract_name_and_version.outputs.minor_ver }}
          cache-to: type=inline
